#pragma once

enum HandleWordStatus
{
    OK,
    GOT_ERROR,
    WRONG_ORDER,
    NOT_JAPANESE_WORD,
    DICT_NOT_ANSWER,
    NO_SPEACH_PART,
    NO_FOUND_WORD,
    GOT_END_WORD,
    GOT_DOUBLED_WORD,
    CANT_JOIN_WORDS,
    GAME_NOT_FOUND,
    GAME_STOPPED,
    NO_FOUND_PLAYER,
};